<?php
namespace backend\models;

use Yii;
use yii\db\ActiveRecord;
use backend\behavior\EventLogsBehavior;

class Leather extends Ticket
{

    const TEMPLATE = 'leather';

    public function rules(){
        return [
            [['param1n', 'param5n', 'param34_14n', 'discount', 'quantity'], 'integer'],
            [['cost'], 'double'],
            ['quantity', 'default', 'value' => 1],
            [[
                'caption',
                'orderId',
                'clientId',
                'caption',
                'marking',
                'wear',
                'color',
                'services',
                'param1',
                'param1n',
                'param2',
                'param3',
                'param4',
                'param5',
                'param5n',
                'param6',
                'param7',
                'param8',
                'param9',
                'param10',
                'param11',
                'param12',
                'param13',
                'pollution',
                'param14',
                'param15',
                'param16',
                'param17',
                'param18',
                'param19',
                'param20',
                'param21',
                'param22',
                'param23',
                'param24',
                'param25',
                'param26',
                'param27',
                'param28',
                'param29',
                'param30',
                'param31',
                'param32',
                'param33',
                'param34',
                'param34_1',
                'param34_2',
                'param34_3',
                'param34_4',
                'param34_5',
                'param34_6',
                'param34_7',
                'param34_8',
                'param34_9',
                'param34_10',
                'param34_11',
                'param34_12',
                'param34_13',
                'param34_14',
                'param34_14n',
                'param34_15',
                'param34_16',
                'param34_17',
                'param34_18',
                'param34_19',
                'other',
                'param35',
                'param36',
                'param37',
                'param38',
                'param39',
                'param40',
                'param41',
                'param42',
                'param43',
                'param44',
                'param45',
                'param46',
                'param47',
                'param48',
                'param49',
                'param50',
                'param51',
                'param52',
                'param53',
                'param54',
                'param55',
                'param56',
                'param57',
                'param58',
                'param59',
                'param60',
                'param61',
                'param62',
                'param63',
                'param64',
                'param65',
                'param66',
                'param67',
                'param68',
                'param69',
                'param70',
                'param71',
                'param72',
                'param73',
                'param74',
                'param75',
                'param76',
                'salinity',
            ], 'safe'],
        ];
    }

    public function attributeLabels(){
        return [
            'caption' => 'Наименование изделия',
            'marking' => 'Маркировка',
            'wear' => 'Степень износа',
            'color' => 'Цвет',
            'param1' => 'Пуговицы',
            'param1n' => 'Количество',
            'param2' => 'Брошки',
            'param3' => 'Пряжки',
            'param4' => 'Пояс',
            'param5' => 'Молнии',
            'param5n' => 'Количество',
            'param6' => 'Пряжки',
            'param7' => 'Кожаные отделки',
            'param8' => 'Кож/зам отделки',
            'param9' => 'Стразы',
            'param10' => 'Клееные украшения',
            'param11' => 'Заклепки',
            'param12' => 'Кнопки',
            'param13' => 'Искусственные материалы, запрещенные к химчистке',
            'pollution' => 'Степень загрязнения',
            'param14' => 'Изменение цвета',
            'param15' => 'Выгор',
            'param16' => 'Желтизна',
            'param17' => 'Разнооттеночность',
            'param18' => 'Из разных кусков по выделке',
            'param19' => 'Наличие клеевых деталей',
            'param20' => 'Отслоение',
            'param21' => 'Деформация',
            'param22' => 'Нарушение формоустойчивости',
            'param23' => 'Царапины',
            'param24' => 'Светлые пятна',
            'param25' => 'Вытравки',
            'param26' => 'Морщины',
            'param27' => 'Складки',
            'param28' => 'Жировые налеты',
            'param29' => 'Уплотнения без ворса',
            'param30' => 'Рыхлость',
            'param31' => 'Волнистость',
            'param32' => 'Ворсистость',
            'param33' => 'Подрезы',
            'param34' => 'Выхваты(несквозной порез)',
            'param34_1' => 'Задиры лицевого слоя',
            'param34_2' => 'Белёсость от трения',
            'param34_3' => 'Истончение кожи',
            'param34_4' => 'Трещины',
            'param34_5' => 'Сваленность меха',
            'param34_6' => 'Поредение меха',
            'param34_7' => 'Потертости',
            'param34_8' => 'Ласы',
            'param34_9' => 'Блеск',
            'param34_10' => 'Затеки',
            'param34_11' => 'Срыв красителя',
            'param34_12' => 'Заломы',
            'param34_13' => 'Расхождение швов',
            'param34_14' => 'Дырки',
            'param34_14n' => 'Количетсво',
            'param34_15' => 'Зацепы',
            'param34_16' => 'Пиллингование',
            'param34_17' => 'Запалы и ласы от глажения',
            'param34_18' => 'Сход пленочного покрытия',
            'param34_19' => 'Слабость закрепления покрытия или красителя',
            'other' => 'Прочие дефекты',
            'param35' => 'Кофе',
            'param36' => 'Чай',
            'param37' => 'Какао',
            'param38' => 'Соки',
            'param39' => 'Шоколад',
            'param40' => 'Масло',
            'param41' => 'Жир',
            'param42' => 'Фрукты',
            'param43' => 'Соус',
            'param44' => 'Вино',
            'param45' => 'Пиво',
            'param46' => 'Кровь',
            'param47' => 'Краска',
            'param48' => 'Чернила',
            'param49' => 'Шариковая/геливая ручка',
            'param50' => 'Масло',
            'param51' => 'Жир',
            'param52' => 'ГСМ',
            'param53' => 'Пятно от дождя',
            'param54' => 'Уличная грязь',
            'param55' => 'Слюна животных',
            'param56' => 'Стиральный порошок',
            'param57' => 'Клей',
            'param58' => 'Ржавчина',
            'param59' => 'Серость',
            'param60' => 'Покарсы после стирки',
            'param61' => 'Потожировые пятна',
            'param62' => 'Застаревшее пятно',
            'param63' => 'Губная помада',
            'param64' => 'Тушь',
            'param65' => 'Крем',
            'param66' => 'Дезодорант',
            'param67' => 'Зеленка',
            'param68' => 'Йод',
            'param69' => 'Мази',
            'param70' => 'Растворы',
            'param71' => 'Пятна неизвестного происхождения',
            'param72' => 'Химчитска',
            'param73' => 'Аква чистка',
            'param74' => 'Стирка',
            'param75' => 'ВТО',
            'param76' => 'Пятно',
            'cost' => 'Стоимость',
            'discount' => 'Скидка,%',
            'services' => 'Доп. услуги',
            'salinity' => 'Степепь засаленности',
            'quantity' => 'Количество'
        ];
    }
}
